// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ListStoreReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"pageSize,default=20"`
}

type ListStoreResp struct {
	Total int64       `json:"total"`
	List  []StoreInfo `json:"list"`
}

type LoginReq struct {
	LoginName string `json:"loginName"`
	Password  string `json:"password"`
	StoreCode string `json:"storeCode,optional"`
}

type LoginResp struct {
	Token       string   `json:"token"`
	ExpireAt    int64    `json:"expireAt"`
	EmployeeId  int64    `json:"employeeId"`
	Name        string   `json:"name"`
	Permissions []string `json:"permissions"`
}

type OpenShiftReq struct {
	StoreId  int64  `json:"storeId"`
	OpenCash string `json:"openCash"`
}

type OpenShiftResp struct {
	ShiftId int64 `json:"shiftId"`
}

type StoreInfo struct {
	Id      int64  `json:"id"`
	Name    string `json:"name"`
	Code    string `json:"code"`
	Address string `json:"address"`
	Status  string `json:"status"`
}
