// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type GroupInfo struct {
	Id         int64        `json:"id"`
	Name       string       `json:"name"`
	GroupType  string       `json:"groupType"`
	SelectType string       `json:"selectType"`
	Required   bool         `json:"required"`
	Options    []OptionInfo `json:"options"`
}

type MenuReq struct {
	StoreId int64 `form:"storeId"`
}

type MenuResp struct {
	List []SpuInfo `json:"list"`
}

type OptionInfo struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Price string `json:"price"`
}

type SpuInfo struct {
	Id                 int64       `json:"id"`
	Name               string      `json:"name"`
	BasePrice          string      `json:"basePrice"`
	ProductionDeptType string      `json:"productionDeptType"`
	Groups             []GroupInfo `json:"groups"`
}
