// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CheckoutReq struct {
	OrderId        int64  `json:"orderId"`
	PayMethod      string `json:"payMethod"`
	DiscountAmount string `json:"discountAmount,optional"`
	ReceivedAmount string `json:"receivedAmount"`
}

type CheckoutResp struct {
	BillId        int64  `json:"billId"`
	BillNo        string `json:"billNo"`
	PayableAmount string `json:"payableAmount"`
	ChangeAmount  string `json:"changeAmount"`
}
