// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateOrderReq struct {
	TableId int64          `json:"tableId"`
	Items   []OrderItemReq `json:"items"`
}

type CreateOrderResp struct {
	OrderId     int64  `json:"orderId"`
	OrderNo     string `json:"orderNo"`
	TotalAmount string `json:"totalAmount"`
}

type OpenTableReq struct {
	TableId     int64 `json:"tableId"`
	PeopleCount int   `json:"peopleCount"`
}

type OpenTableResp struct {
	OrderId int64  `json:"orderId"`
	OrderNo string `json:"orderNo"`
}

type OrderItemReq struct {
	SpuId           int64   `json:"spuId"`
	Qty             int     `json:"qty"`
	Remark          string  `json:"remark,optional"`
	SpecOptionId    int64   `json:"specOptionId,optional"`
	MethodOptionIds []int64 `json:"methodOptionIds,optional"`
	AddonOptionIds  []int64 `json:"addonOptionIds,optional"`
}

type RefundItemReq struct {
	Reason string `json:"reason"`
}

type RefundItemResp struct {
	Ok bool `json:"ok"`
}
